sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-016
env:
  global:
    -
      # LTD_AWS_ID
      secure: s5MdD3cTjpl+eVKkN/BloZkYN3JEH7ygxhxdn/ZOFwt9WEsSOl/q3+PU2qd0mWgF5zOQQ1LCPewPkqxGQubbYTtsaLmN25ZgYNTUAAGMXeBZEMbsvE74fhBPHfI1B4LmbjlhtPF/mRbYX0XFo2lgGxW7W/pcwyJX6OCsuRvG5+yFrNAFI6IJE3NPocewALw8Op+T2AJBM+nhWwDXd2zyTNdd5PCZkZgcS8Y/GR17cVUzFSOHGOnAtTiAmpONyU/deTXfz1jAaf3NhG3Hcr5fCKvqNWWTe7+YAiSfDpqhUoB5GIvsYOGolyih+Bp09E/Zs20o95v8APCO1XIuYYnzaCun9Usl0a5NOYC4rxEvjV6jzZEvYiFIzkaq3V+e6dQeUdHSkKGFcP4fJvB2nfipva0GncjnAdumcRiL+WiMe4xQeHit6Hbq+XE3uL6V0P3y3zE3K187KpYMFTbTIkJ8K6JyeNs43uuAWFtBTlBqEbjz6ETiSLULoLss/jpWImxvJTMntE1e72Kl2hb4wslr0mlA6mQfqiaj5mMqugQPywG8/fWfIhBiwQiyEjUryX5x/zf5FWjo0lKnyNVAb6OqGyAT5/3LwKtYFzmJjYTnQpWsRyE2GEusLMqBoCXHTi5gsuC8NWbi/z72nEHEQ6nzkjiCMUnnjSh8GvhP0YDptbk=
    -
      # LTD_AWS_SECRET
      secure: VvZQDKMGJCf2bqNTganY172pRmg9aCIV4iTgv0+Wr5iPJY10FxXRP0tzcJQTPbGNDi5++AqIOjpt0glCCXcOC7soC3LBwhwS1Aq+z52hrmUVEk5jiQsXKilYPw1t/BKQRWcCUbQvUjM41l3V7CdPeiH+foIAX6S06fte83jHlGtiVJWqNNuUjUPzc0/8QFM+0VQUYs19z3mARqws26dBVHQZlp6xD4oKu4tiu9LZy6qisG3gwenogZ7XMQ5ydoaXmShGBdwyhtvTivJr+Ai2KirkpS9RiBR1CEuLvg9QetWrWfMK5sVkXEcy64SRBKcZSo4wW109qZeKISJlG8t8uZZsYPAEifm9BA1nlxujlqAiQWsGgVVM1oxDyKW15xSro0Igk88LCh+Mastt4NAj3CgTHYCFs8OSortdyePgOLdrTYAf5uqvgHJrOdTiKH7j/nphtfiQ2V0Trmv0aZLzLNtZGnb5c02efbXxb1kid7/IR0aT8pz5Upr9K3fxpdrclS6RzAM5JuPtheO78UN8DQwQokfwyv8J8sZkhajOnkV7PFMubQVNcNXmLmA3KtgMZatrmO9lIQNlGCHc+TDfQ20b+xEKjOokQxAWMp88aN5xHXNv0moz63LEeeCAx2kubOkYhPz1uhqWteC3hQlsziRZptQuajRPZaNbBr0w4TE=
    -
      # LTD_USERNAME
      secure: fUc4s+wdWfIgkTjt1zP3bge6/U3cWrz15ruIwYMBsinRixJqMDV4a4IxfkNxJeUifLhy7OxEpXHEzDFqpeFUjwm2wPPxdJ8GH+tEHkwZFX6BPf/syquIILVQ6CP4/HhI6CTlrHthh00Qsy/7dqhSa5AR+JM7miwMECclmy9IAaeMpPQK0lG2IHNCvcDuY6BAmPtNMwWzVqprD2w1gshcjjLaudg1cleC/FDEhgRl/onnK5BbQTYqYkF3aK1TcVLnqQ3YoWn/LvezB+mKqcQu8otvMKiALvZUVp3MuCE3QbqzvOQuqGlWDGiMeh593GZ+lSv9oWzK11kXMkhZLk0mUcI1uLSVRWxmCq+I0WQf1JbBe9bcMvnQ8a4HzvIDMcAd5x3JtY8hb0CzsmbUDFn7bmk/3FWWsAAVD7k4NIVkSQL4D9gB5U/sYribg0KNIkReg2awCB1AQ/Hlm+ofromiR6Y8C8FT2GMVgWqVSV8jBGN/AMIa9KCymid/c+c+mSsc05ov1LqQzpHBOXzP5olJyYaB3KQnZC6Owqr+OyF+v4y4gjLiIRKFVdj5PpJJvw/nO0vZW1WsgQkPIv3Dsd22GKQotLUB6ZbCbvfyHMNOPzmbRV7YP8fG313J5YLrglQRz1zMXWZgkjRrTOmx416ospxhGVjh6DzgraWkNf+0yqg=
    -
      # LTD_PASSWORD
      secure: QBh5BGdCRN/OE+j2NjEnRi6UEPs7IMqPaVe5TOaxBOe/5xyLCUfOqLnchWOtXkqzCcmsDB9lv0YBaJuDZeUeVhBbtigDA8abBNIQjvY6PwaQWZHG7+jtYFF9RSR+1psfpb9jcn1jbYXrcgG5zFfF6RwRpqd5cXX8N+a1x+5JIXUmPOTKtwVLoQ/TL477NBmU/hmDqevxUDmp54qtlUKs3mbdU933cbH9S0/jiAUzUwQQurJxs6Y5RhOmlXTgsKICsGg3JkKdPKekJlbnThJus0txuaCAM2B9CxDjvycaH+oNGLm+esG865wALBaseo+Xdwgv1WAxUOGTl/PJEoHol1lrMXJRLlfBjNfBVmq/XSq9M12aVDdInjiot/NLabOmbjadhkg1tNmXNFKxkeZGs4MJP5JSpURHWKIcjOLV/6uzjIvYQ3UgarF7dVs4Ix6HQyzCxqIbHdjXNq4UPszDq/Q2bADEX9W1hZoL0rwe17QsvOPGUjye2c+npfkH6VptrngwbE/9kAkMt3xUBovewvqkHc6aoEVqFN0eeVEFe2lr+euiVYVnFdb7OXakrXVb8+ui76cgySgnIivScPF/J09teiWs01ArVlwd1XZOR0IPP+QfFR/qbL6qvP9dAx0Xvr2s7trl7lXdJQyHnW4AJvIjJwTg5V0/kCubzMviRX4=
